name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "file:./dev.db"
      AUTH_SECRET: "ci-secret-not-used-for-anything-real-0123456789"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run db:deploy
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run build
